/*
Skycons is a set of ten animated weather glyphs, procedurally generated by JavaScript using the HTML5 canvas tag.
http://darkskyapp.github.io/skycons/
*/
var skycons = new Skycons();

// you can add a icon to a html canvas. simply supply its element id and the weather you want to show.

skycons.add("day1", Skycons.CLEAR_DAY);
skycons.add("day2", Skycons.CLOUDY);
skycons.add("day3", Skycons.RAIN);

// start all icons animation!
skycons.play();
// update a icon on canvas by its id

//select city


//show taipei's weather
showData(getData('taipei'));
// get city's data
function getData(city){
  var url ='https://query.yahooapis.com/v1/public/yql?q=select%20*%20from%20weather.forecast%20where%20woeid%20in%20(select%20woeid%20from%20geo.places(1)%20where%20text%3D%22'+city+'%22)&format=json&env=store%3A%2F%2Fdatatables.org%2Falltableswithkeys'
  return url
};
// show city's data
function showData(end){
  $.getJSON(end,function(data){
      var currentTemp = data.query.results.channel.item.condition.temp ;
      var currentTempFinal = Math.round((currentTemp-32)*5/9);
      $(".temperature").text(currentTempFinal);


      var currentState = data.query.results.channel.item.condition.code;
      switch (parseInt(currentState)) {
        case 32:
        case 34:
        case 36:
        skycons.set("today",Skycons.CLEAR_DAY);
        break;
        case 31:
        case 33:
        skycons.set("today",Skycons.CLEAR_NIGHT);
        break;
        case 11:
        case 12:
        skycons.set("today",Skycons.RAIN);
        break;
        case 30:
        case 28:
        skycons.set("today",Skycons.PARTLY_CLOUDY_DAY);
        break;
        case 29:
        case 27:
        skycons.set("today",Skycons.PARTLY_CLOUDY_NIGHT);
        break;
        case 26:
        skycons.set("today",Skycons.CLOUDY);
        break;
        case 24:
        case 23:
        skycons.set("today",Skycons.WIND );
        break;
        case 20:
        case 21:
        case 22:
        skycons.set("today",Skycons.FOG);
        break;
      }


// change  forecast123's data
var currentStateText = data.query.results.channel.item.condition.text;
$('#weatherState').text(currentStateText);
var currentDate = data.query.results.channel.item.forecast[0].date;
$('.date').text(currentDate);
var forecastDay1 = data.query.results.channel.item.forecast[1].date;
$('#forecast1').text(forecastDay1);
var forecastDay2 = data.query.results.channel.item.forecast[2].date;
$('#forecast2').text(forecastDay2);
var forecastDay3 = data.query.results.channel.item.forecast[3].date;
$('#forecast3').text(forecastDay3);

// change forecast123's low-high tem
var forecastLow1 = data.query.results.channel.item.forecast[1].low;
$('#low1').text(Math.round((forecastLow1-32)*5/9));
var forecastHigh1 = data.query.results.channel.item.forecast[1].high;
$('#high1').text(Math.round((forecastHigh1-32)*5/9));
var forecastLow2 = data.query.results.channel.item.forecast[2].low;
$('#low2').text(Math.round((forecastLow2-32)*5/9));
var forecastHigh2 = data.query.results.channel.item.forecast[2].high;
$('#high2').text(Math.round((forecastHigh2-32)*5/9));
var forecastLow3 = data.query.results.channel.item.forecast[3].low;
$('#low3').text(Math.round((forecastLow3-32)*5/9));
var forecastHigh3 = data.query.results.channel.item.forecast[3].high;
$('#high3').text(Math.round((forecastHigh3-32)*5/9));

//get forecast123's data

var forecastCode1=data.query.results.channel.item.forecast[1].code;
var forecastCode2=data.query.results.channel.item.forecast[2].code;
var forecastCode3=data.query.results.channel.item.forecast[3].code;

skycons.set("day1",getforecast (forecastCode1));
skycons.set("day2",getforecast (forecastCode2));
skycons.set("day3",getforecast (forecastCode3));

function getforecast(forecast){
  switch (parseInt(forecast)){
    case 32:
    case 34:
    case 36:
      return Skycons.CLEAR_DAY;
      break;
    case 31:
    case 33:
      return Skycons.CLEAR_NIGHT;
      break;
    case 11:
    case 12:
      return Skycons.RAIN;
      break;
    case 30:
    case 28:
      return Skycons.PARTLY_CLOUDY_DAY;
      break;
    case 29:
    case 27:
      return Skycons.PARTLY_CLOUDY_NIGHT;
      break;
    case 26:
      return Skycons.CLOUDY;
      break;
    case 24:
    case 23:
      return Skycons.WIND;
      break;
    case 20:
    case 21:
    case 22:
      return Skycons.FOG;
      break;
    }
    }
});
}

$('#dropdown li a').each(function () {
      var vm = this;
      var city = $(this).text();
      console.log(city);
    $.getJSON(getData(city),function(data){
      var currentTemp = data.query.results.channel.item.condition.temp ;
      var currentTempFinal = Math.round((currentTemp-32)*5/9);
      // console.log(this);
      vm.append(currentTempFinal + "℃");
    })
  });
  $('#dropdown li').on('click', function(){
    var city = $(this).text();
    $('#city').text(city);
    showData(getData(city));
    });
